// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfLFEzlxJqXHbsxEY7D53JR55q7whUt1Y',
    appId: '1:86749474328:web:58ef47434ea564e8371d6d',
    messagingSenderId: '86749474328',
    projectId: 'acti-miage',
    authDomain: 'acti-miage.firebaseapp.com',
    databaseURL: 'https://acti-miage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acti-miage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfJi-eLc5kAITYQKQvPwpvGLjIbFgedec',
    appId: '1:86749474328:android:520820d617f638dc371d6d',
    messagingSenderId: '86749474328',
    projectId: 'acti-miage',
    databaseURL: 'https://acti-miage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acti-miage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDzKh6V-NNjRCqUbED6hcwdpkfqArpimw',
    appId: '1:86749474328:ios:e5f35cd41f0e5e8a371d6d',
    messagingSenderId: '86749474328',
    projectId: 'acti-miage',
    databaseURL: 'https://acti-miage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acti-miage.appspot.com',
    iosBundleId: 'com.example.appProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDzKh6V-NNjRCqUbED6hcwdpkfqArpimw',
    appId: '1:86749474328:ios:c0bc9a22be8b3edb371d6d',
    messagingSenderId: '86749474328',
    projectId: 'acti-miage',
    databaseURL: 'https://acti-miage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'acti-miage.appspot.com',
    iosBundleId: 'com.example.appProjet.RunnerTests',
  );
}
